version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bootsnap
    versions:
    - 1.7.0
    - 1.7.1
    - 1.7.2
    - 1.7.3
    - 1.7.4
  - dependency-name: rubocop
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
    - 1.12.1
    - 1.13.0
    - 1.9.1
  - dependency-name: jwt
    versions:
    - 2.2.3
  - dependency-name: oj
    versions:
    - 3.11.3
    - 3.11.4
    - 3.11.5
  - dependency-name: ruby-saml
    versions:
    - 1.12.1
    - 1.12.2
  - dependency-name: sidekiq
    versions:
    - 6.2.0
    - 6.2.1
  - dependency-name: listen
    versions:
    - 3.5.0
  - dependency-name: rails
    versions:
    - 6.1.2
    - 6.1.2.1
    - 6.1.3.1
  - dependency-name: liquid
    versions:
    - 5.0.1
  - dependency-name: awesome_print
    versions:
    - 1.9.2
  - dependency-name: puma
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: groupdate
    versions:
    - 5.2.2
