kind: pipeline
name: cd

clone:
  disable: true

concurrency:
  limit: 1

steps:
- name: update_docker
  image: docker:git
  environment:
    POMPA_DOCKER_DEPLOY_KEY:
      from_secret: pompa_docker_deploy_key
  commands:
  - export SHORT_COMMIT="$(echo $DRONE_COMMIT | cut -c1-7)"
  - mkdir -p ~/.ssh
  - echo -ne "$POMPA_DOCKER_DEPLOY_KEY" > ~/.ssh/id_rsa
  - ssh-keyscan -H github.com > ~/.ssh/known_hosts
  - chmod 600 ~/.ssh/id_rsa ~/.ssh/known_hosts
  - git clone git@github.com:m1nl/pompa-docker.git
  - cd pompa-docker
  - git config user.email "drone@nalewajski.pl"
  - git config user.name "Drone CI"
  - git submodule init -- app/pompa-api
  - git submodule update --checkout -- app/pompa-api
  - cd app/pompa-api
  - git checkout $DRONE_COMMIT
  - cd ../..
  - git add app/pompa-api
  - git commit --allow-empty -m "update pompa-api with $SHORT_COMMIT ($DRONE_COMMIT_MESSAGE) by $DRONE_COMMIT_AUTHOR"
  - git push origin master

trigger:
  branch:
  - master
  event:
  - push
