redis_default: &redis_default
  driver: hiredis
  pool_size: 15
  url: "unix:///var/run/redis/redis-server.sock"
  db: 0

default: &default
  log_level: "info"
  code_length: 7
  batch_size: 1000
  url: /api
  origins: ""
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
  sendfile_header: ""
  endpoints:
    admin: true
    public: true
    sidekiq_console: false
  model_cache:
    enable: true
    expire: 300
  response_cache:
    enable: true
    expire: 300
  lock:
    retry_delay: 0.2
    retry_count: 50
  worker:
    queue_timeout: 30
    refill_interval: 120
    expiry_timeout: 300
  mailer:
    idle_timeout: 180
    debug_email_content: false
  campaign:
    sync_interval: 20
    victim_batch_size: 3
    error_threshold: 6
    respawn_interval: 300
  victim:
    email_timeout: 300
    retry_threshold: 5
    expose_header: "X-Victim-Code"
  template:
    base_url: "http://localhost:3000/api/public"
    report_url: "{{ template.base_url }}/?g={{ goal.code }}&v={{ victim.code }}{% if location != blank %}&l={{ location | encrypt: true }}{% endif %}"
    static_resource_url: "{{ template.base_url }}/?r={{ resource.code }}&t={{ resource.cache_key | urlsafe_digest }}{% if filename != blank %}&f={{ filename | encrypt: false }}{% endif %}"
    dynamic_resource_url: "{{ template.base_url }}/?r={{ resource.code }}&v={{ victim.code }}{% if filename != blank %}&f={{ filename | encrypt: false }}{% endif %}"
  report:
    cookie_name: "pompa"
  redis:
    <<: *redis_default

production:
  <<: *default
  redis:
    <<: *redis_default
    db: 1
    pool_size: 25

development:
  <<: *default
  origins: "*"
  log_level: "debug"

test:
  <<: *default
