redis_default: &redis_default
  driver: hiredis
  pool_size: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: "<%= ENV.fetch('POMPA_REDIS_URL') { 'unix:///var/run/redis/redis-server.sock' } %>"
  db:
    global: 0
    cache: 10

default: &default
  log_level: "info"
  code_length: 7
  batch_size: 1000
  url: /api
  origins: ""
  trusted_proxies:
    - "127.0.0.1"
    - "::1"
  sendfile_header: ""
  endpoints:
    admin: true
    public: true
  authentication:
    enabled: false
    authentication_timeout: 300
    authentication_lifetime: 3600
    access_timeout: 300
    temporary_access_timeout: 5
    token_refresh_margin: 90
    auto_create_user: false
    allowed_roles: []
    role_attribute_name: "role"
    role_attribute_name_format: "urn:oasis:names:tc:SAML:2.0:attrname-format:basic"
  model_cache:
    enable: true
    expire: 300
  response_cache:
    enable: true
    expire: 300
  lock:
    retry_delay: 0.2
    retry_count: 50
  worker:
    queue_timeout: 30
    refill_interval: 120
    expiry_timeout: 300
  mailer:
    idle_timeout: 180
    debug_email_content: false
    extra_headers:
      - name: "X-Phishing-Simulation"
        value: 1
  campaign:
    sync_interval: 20
    victim_batch_size: 3
    error_threshold: 6
    respawn_interval: 300
    public_redis_db: global
  victim:
    email_timeout: 300
    retry_threshold: 5
    expose_header: "X-Victim-Code"
  template:
    base_url: "<%= ENV.fetch('POMPA_BASE_URL') { 'http://localhost:3000/api/public/' } %>"
    report_url: >-
      {%- assign query = '?g=' | append: goal.code | append: '&v=' | append: victim.code -%}
      {%- unless location == blank -%}{%- assign location = location | encrypt: true -%}{%- assign query = query | append: '&l=' | append: location -%}{%- endunless -%}
      {{ template.base_url | append_url: query | string }}
    static_resource_url: >-
      {%- assign timestamp = resource.cache_key | urlsafe_digest -%}
      {%- assign query = '?r=' | append: resource.code | append: '&t=' | append: timestamp -%}
      {%- unless filename == blank -%}{%- assign filename = filename | encrypt: false -%}{%- assign query = query | append: '&f=' | append: filename -%}{%- endunless -%}
      {{ template.base_url | append_url: suffix | append_url: query | string }}
    dynamic_resource_url: >-
      {%- assign query = '?r=' | append: resource.code | append: '&v=' | append: victim.code -%}
      {%- unless filename == blank -%}{%- assign filename = filename | encrypt: false -%}{%- assign query = query | append: '&f=' | append: filename -%}{%- endunless -%}
      {{ template.base_url | append_url: suffix | append_url: query | string }}
  report:
    cookie_name: "pompa"
  redis:
    <<: *redis_default

production:
  <<: *default
  redis:
    <<: *redis_default
    db:
      global: 1
      cache: 11

development:
  <<: *default
  origins: "*"
  log_level: "debug"

test:
  <<: *default
